# Generated by Django 3.2.16 on 2022-12-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="tag",
            managers=[],
        ),
        migrations.RenameField(
            model_name="item",
            old_name="tag",
            new_name="tags",
        ),
    ]
