# Generated by Django 3.2.16 on 2022-11-06 15:04

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20221030_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Используйте только цифры, буквы латиницы и символы - и _', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+(?:[_|-][a-z0-9]+)*$')], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(validators=[catalog.validators.validate_text], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Используйте только цифры, буквы латиницы и символы - и _', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+(?:[_|-][a-z0-9]+)*$')], verbose_name='Слаг'),
        ),
        migrations.CreateModel(
            name='PhotoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
            },
        ),
    ]
