# Generated by Django 3.2.16 on 2022-11-13 13:05

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20221107_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='photoitem',
            options={'verbose_name': 'фото товара', 'verbose_name_plural': 'фото товара'},
        ),
        migrations.AlterModelOptions(
            name='photositem',
            options={'verbose_name': 'фото товара', 'verbose_name_plural': 'фотогалерея товаров'},
        ),
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(related_name='items', to='catalog.Tag', verbose_name='теги'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(validators=[catalog.validators.validate_text], verbose_name='описание'),
        ),
    ]
