# Generated by Django 3.2.16 on 2022-11-13 15:52

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20221113_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoitem',
            options={'verbose_name': 'превью товара'},
        ),
        migrations.AlterField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='на главной'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(validators=[catalog.validators.validate_text], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='photoitem',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='photoitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='photositem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.item'),
        ),
    ]
