# Generated by Django 3.2.16 on 2022-11-15 16:52

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_item_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Используйте только цифры, буквы латиницы и символы - и _', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+(?:[_|-][a-z0-9]+)*$')], verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.SmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(validators=[catalog.validators.validate_text], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='photoitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Используйте только цифры, буквы латиницы и символы - и _', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9]+(?:[_|-][a-z0-9]+)*$')], verbose_name='слаг'),
        ),
    ]
