# Generated by Django 3.2.16 on 2022-12-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemrating',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
